version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "gomod"
    directory: "/qubership-apihub-backend/qubership-apihub-service/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "gomod"
    directory: "/qubership-api-linter-service/qubership-api-linter-service/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "gomod"
    directory: "/qubership-apihub-agents-backend/qubership-apihub-agents-backend/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "gomod"
    directory: "/qubership-apihub-commons-go/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "go"

  - package-ecosystem: "npm"
    directory: "/qubership-apihub-ui/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/qubership-apihub-build-task-consumer/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "npm"
    directory: "/qubership-apihub-ui-tests/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: "docker"
    directory: "/qubership-apihub-backend/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/qubership-apihub-ui/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/qubership-apihub-build-task-consumer/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/qubership-api-linter-service/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "docker"
    directory: "/qubership-apihub-agents-backend/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore: deps:"
    labels:
      - "dependencies"
      - "docker"
