name: CI

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  packages: write
  pull-requests: read

jobs:
  ci:
    uses: ./.github/workflows/monorepo-ci.yml
    secrets: inherit
    with:
      modules-file: ci/modules.yaml
      run-e2e-compose: true
      run-e2e-kind: true
